### ISSUE TITLE
Mastodon Diff Tool

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon-git#11]
**This is part of mastodon-sc/mastodon-tomancak#15**

Develop a tool that can display the differences between two versions of a mastodon project.

It should be able to display the following things:
* spots added / removed
* links added / removed
* changed spot id
* changed spot label, positions, covariance matrix
* display changes in tags

It's maybe feasible to ignore things like: gui settings, computed features etc.

This tool should be able to produce a human readable output as well as a machine readable ".mastodonpatch".

The tool should also be able to apply the machine readable ".mastodonpatch" to a mastodon project.

# TODO

- [ ] Data structure that contains insert, delete and update operations for spots. The update operations should lead from version A to version B
  - [ ] List with inserts
  - [ ] List with deletes 
  - [ ] List with updates
- [ ] Use git graph, to differentiate between spots that need to be updated or inserted/removed
  - [ ] Spot existed on last common commit of version A and version B leads to an update operation
  - [ ] Spot did not exist on last common commit of version A and version B leads to an insert operation
  - [ ] Spot existed on last common commit of version A and version B and does not exist anymore leads to a delete operation
