### ISSUE TITLE
Move CopyModelUtils and ModelAsserts to mastodon core.

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon-git#15]
Mastodon git has two utility classes that are probably of interest for all mastodon projects so the should be moved to the mastodon core. These classes are:

[CopyModelUtils](https://github.com/mastodon-sc/mastodon-git/blob/adapt-beta-27/src/main/java/org/mastodon/mamut/collaboration/utils/CopyModelUtils.java)
[ModelAsserts](https://github.com/mastodon-sc/mastodon-git/blob/adapt-beta-27/src/test/java/org/mastodon/mamut/collaboration/utils/ModelAsserts.java)

### TODOs
- [ ] Open a PR on Mastodon core
- [ ] Make the CopyModelUtils more flexible
  - [ ] Allow to rename cells (for example prefix)
  - [ ] Allow to provide a transformation for cell position
  - [ ] Whether or not to copy tags
  - [ ] Allow to rename tagset names
  - [ ] ...
- [ ] Change the format of the modelToString to reduce the duplications in the string.
  The format could be:
```
Spot(...) spot tags: <list of spot tags>
  -> link to Spot(...) link tags: <list of edge tags>
  <list all outgoing edges>
```
