### ISSUE TITLE
Adapt to Mastodon's new ProjectModel

### ISSUE THREAD

**Issue by maarzt** [mastodon-sc/mastodon-git#3]
The mastdon-git project is not compatible with the latest mastodon core version. It needs to be updated.

This issue is addressed in #4 

## Problem

Mastodon-git cannot be installed with the latest mastodon 1.0.0-beta-28. Fiji instead crashes and complains about undefined classes or undefined methods.

## Expected Behavior

It should be possible to run mastodon-git with the latest mastodon 1.0.0-beta-28. All functions that are described in the documentation: [How to share a Mastodon project?](doc/share_tutorial.md) [How to contribute to as share Mastodon Project?](doc/contribute_tutorial.md) should work as expected.
(An SNAPSHOT version of mastodon-git and mastodon-collections is on the `Maarzt` update site.  An up to date Fiji with 'TomancakLab' and 'Maarzt' update sites activate should allow to go through all the steps in the mastodon-git tutorials.)

## TODOs

- [x] Make this repository compatible with mastodon version 1.0.0-beta-27 and the Mastodon-Dev Fiji update site.
- [x] Add a unit test to make sure everything still works. The unit test could simulate:
  - 1. creating a shared project
  - 2. cloning a share project
  - 3. two people contributing simultaneously
- [x] **Problem: model.getGraph().notifyGraphChanged()** needs to be called, after reload from disk, but this breaks the undo redo recorder as demonstrated in the failing UndoRedoTest. The problem is fixed in this PR https://github.com/mastodon-sc/mastodon-collection/pull/16 and there are important unit tests in this PR: https://github.com/mastodon-sc/mastodon/pull/289
- [x] Compile the JAR and put it on the ["Maarzt"](https://sites.imagej.net/Maarzt/) update site that also includes the dependencies.
- [x] Functional testing
- [ ] test branches
- [ ] ask for author name before "commit", "pull", "clone", when it hasn't been set.
- [x] fix typo in share project dialog

**Comment by maarzt** [comment]
Make sure the plugin still works if the dataset is not available on a specific machine:
https://github.com/maarzt/mastodon-git/commit/24dd398362065aac2c920e4ca6aa4f1aa6a457ad#diff-a9ccbd89008809a2a88004294ab8cb578090ec58e31bcae89b3fb37bb073b4a6
